### ISSUE TITLE
existing metadata or annotation on vanity url is removed

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift-helpers#128]
with our approach to delete and create vanity url with updated certs, it is removing the existing annotations on the route
for ex:
```
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/rate-limit-connections: 'true'
    haproxy.router.openshift.io/rate-limit-connections.concurrent-tcp: '100'
    haproxy.router.openshift.io/rate-limit-connections.rate-http: '200'
    haproxy.router.openshift.io/rate-limit-connections.rate-tcp: '500'
```
we have to find a way to keep existing annotations of the route in place.
